- nodeset:
    name: emea-node
    nodes:
      - name: node1
        label: ubuntu-bionic
         
- nodeset:
    name: nafta-node
    nodes:
      - name: centos2
        label: centos2

        
#- nodeset:
#    name: gate-node
#    nodes:
#     - name: gate
#        label: centos76 

- job:
    name: democbuildjob
    run: playbooks/democbuild.yml
    parent: base
    
- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base
    
    
- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base
    

- project:
#    vars:
#      myname: "juhi"
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node   
    check_nafta_cpjt:
      jobs:
        - democbuildjob:
            host-vars: 
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea-node
