- nodeset:
    name: emea-node
    nodes:
      - name: node1
        label: ubuntu-bionic
         
- nodeset:
    name: nafta-node
    nodes:
      - name: centos2
        label: centos2

        
#- nodeset:
#    name: gate-node
#    nodes:
#     - name: gate
#        label: centos76 

- job:
    name: democbuildjob
    run: playbooks/democbuild.yml
    parent: base

- project:
#    vars:
#      myname: "juhi"
    check_nafta_cpjt:
      jobs:
        - democbuildjob:
            irrelevant-files:
              - .zuul.yaml
              - playbooks
            host-vars: 
              node1:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSC8JkmgdCJ1SyqE3gtXEeyRYdQ2dTpE7oooHmgWW9WuKKBPrDtrfjzPfa9PMX7LSP"
            nodeset: emea-node
