- hosts: all
  tasks:
    - debug:
        msg: "running for c++  demo"
#    - debug: 
#         msg: "{{ emea_jfrog }}"
#    - debug:
#        msg: "{{ nafta_jfrog }}"
        
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo and initialize submodules
      block:
        - name: Clone the repo
          git:
            repo: https://github.com/zuul-hcl-org/ModernCppCI.git
            dest: ~/work/ModernCppCI
        - name: Initialize submodules    
          shell: |
                cd ~/work/ModernCppCI
                git submodule init && git submodule update   
      when: clean_output is succeeded
             
    - name: Build sample project
      shell: |
            cd ~/work/ModernCppCI
            rm -rf Build
            cmake -H. -BBuild
            cd Build
            cmake --build .
      register: build_status
      
    - name: Test sample project
      shell: |
            cd ~/work/ModernCppCI/Build
            ctest -V 
      register: test_status
      
    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ jfrog }}/artifactory/generic-local/ModernCppCIApp_{{ zuul.build }}"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: "{{ jfrog_api_token }}"
        src: ~/work/ModernCppCI/Build/app/ModernCppCIApp
        status_code: 201
        remote_src: yes
      when: test_status is succeeded
